server:
  port: ${PORT:5000}

base-url: /api

spring:
  application:
    name: hexletProject

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jackson:
    serialization:
      fail-on-empty-beans: false

springdoc:
  api-docs:
    path: /swagger.html