server:
  port: ${PORT:5000}

base-url: /welcome

spring:
  application:
    name: hexletProject

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  mvc:
    hiddenmethod:
      filter:
        enabled: true