spring:
  datasource:
    url: "jdbc:h2:./project"
    username: "sa"
    password: ""

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

  jpa:
    show-sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    root: INFO
    web: DEBUG